Erp.BackOffice/Areas/Crm/Models/ProcessStageViewModel.cs
using Erp.BackOffice.App_GlobalResources;
using Erp.Domain.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Erp.BackOffice.Crm.Models
{
    public class ProcessStageViewModel
    {
        public int Id { get; set; }

        [Display(Name = "IsDeleted")]
        public bool? IsDeleted { get; set; }

        [Display(Name = "CreatedUser", ResourceType = typeof(Wording))]
        public int? CreatedUserId { get; set; }
        public string CreatedUserName { get; set; }

        [Display(Name = "CreatedDate", ResourceType = typeof(Wording))]
        public DateTime? CreatedDate { get; set; }

        [Display(Name = "ModifiedUser", ResourceType = typeof(Wording))]
        public int? ModifiedUserId { get; set; }
        public string ModifiedUserName { get; set; }

        [Display(Name = "ModifiedDate", ResourceType = typeof(Wording))]
        public DateTime? ModifiedDate { get; set; }

        [Display(Name = "AssignedUserId", ResourceType = typeof(Wording))]
        public int? AssignedUserId { get; set; }
        public string AssignedUserName { get; set; }

        [Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Error))]
        [StringLength(100, ErrorMessageResourceType = typeof(Error), ErrorMessageResourceName = "StringError", ErrorMessage = null)]
        [Display(Name = "Name", ResourceType = typeof(Wording))]
        public string Name { get; set; }

        [Display(Name = "OrderNo", ResourceType = typeof(Wording))]
        public Nullable<int> OrderNo { get; set; }
        public Nullable<int> ProcessId { get; set; }        
    }
}

Erp.BackOffice/Areas/Crm/Controllers/ProcessStageController.cs
using System.Globalization;
using Erp.BackOffice.Crm.Models;
using Erp.BackOffice.Filters;
using Erp.Domain.Entities;
using Erp.Domain.Interfaces;
using Erp.Domain.Crm.Entities;
using Erp.Domain.Crm.Interfaces;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using Erp.Utilities;
using WebMatrix.WebData;
using Erp.BackOffice.Helpers;

namespace Erp.BackOffice.Crm.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    [Erp.BackOffice.Helpers.NoCacheHelper]
    public class ProcessStageController : Controller
    {
        private readonly IProcessStageRepository ProcessStageRepository;
        private readonly IUserRepository userRepository;

        public ProcessStageController(
            IProcessStageRepository _ProcessStage
            , IUserRepository _user
            )
        {
            ProcessStageRepository = _ProcessStage;
            userRepository = _user;
        }

        #region Index

        public ViewResult Index(int ProcessId, string ProcessEntity)
        {
            IQueryable<ProcessStageViewModel> q = ProcessStageRepository.GetAllProcessStage()
                .Where(item => item.ProcessId == ProcessId)
                .Select(item => new ProcessStageViewModel
                {
                    Id = item.Id,
                    CreatedUserId = item.CreatedUserId,
                    //CreatedUserName = item.CreatedUserName,
                    CreatedDate = item.CreatedDate,
                    ModifiedUserId = item.ModifiedUserId,
                    //ModifiedUserName = item.ModifiedUserName,
                    ModifiedDate = item.ModifiedDate,
                    Name = item.Name,
                    OrderNo = item.OrderNo
                }).OrderBy(m => m.OrderNo);

            ViewBag.ProcessEntity = ProcessEntity;

            return View(q);
        }
        #endregion

        #region Create
        public ViewResult Create(int ProcessId)
        {
            var model = new ProcessStageViewModel();
            model.ProcessId = ProcessId;

            return View(model);
        }

        [HttpPost]
        public ActionResult Create(ProcessStageViewModel model, bool IsPopup)
        {
            if (ModelState.IsValid)
            {
                var ProcessStage = new ProcessStage();
                AutoMapper.Mapper.Map(model, ProcessStage);
                ProcessStage.IsDeleted = false;
                ProcessStage.CreatedUserId = WebSecurity.CurrentUserId;
                ProcessStage.ModifiedUserId = WebSecurity.CurrentUserId;
                ProcessStage.AssignedUserId = WebSecurity.CurrentUserId;
                ProcessStage.CreatedDate = DateTime.Now;
                ProcessStage.ModifiedDate = DateTime.Now;
                ProcessStageRepository.InsertProcessStage(ProcessStage);

                if (IsPopup)
                {
                    return RedirectToAction("_ClosePopup", "Home", new { area = "", FunctionCallback = "ClosePopupAndReloadPage" });
                }
                else
                {
                    TempData[Globals.SuccessMessageKey] = App_GlobalResources.Wording.InsertSuccess;
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }
        #endregion

        #region Edit
        public ActionResult Edit(int? Id)
        {
            var ProcessStage = ProcessStageRepository.GetProcessStageById(Id.Value);
            if (ProcessStage != null && ProcessStage.IsDeleted != true)
            {
                var model = new ProcessStageViewModel();
                AutoMapper.Mapper.Map(ProcessStage, model);

                if (model.CreatedUserId != Erp.BackOffice.Helpers.Common.CurrentUser.Id && Erp.BackOffice.Helpers.Common.CurrentUser.UserTypeId != 1)
                {
                    TempData["FailedMessage"] = "NotOwner";
                    return RedirectToAction("Index");
                }

                return View(model);
            }
            if (Request.UrlReferrer != null)
                return Redirect(Request.UrlReferrer.AbsoluteUri);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(ProcessStageViewModel model, bool IsPopup)
        {
            if (ModelState.IsValid)
            {
                if (Request["Submit"] == "Save")
                {
                    var ProcessStage = ProcessStageRepository.GetProcessStageById(model.Id);
                    AutoMapper.Mapper.Map(model, ProcessStage);
                    ProcessStage.ModifiedUserId = WebSecurity.CurrentUserId;
                    ProcessStage.ModifiedDate = DateTime.Now;
                    ProcessStageRepository.UpdateProcessStage(ProcessStage);

                    if (IsPopup)
                    {
                        return RedirectToAction("_ClosePopup", "Home", new { area = "", FunctionCallback = "ClosePopupAndReloadPage" });
                    }
                    else
                    {
                        TempData[Globals.SuccessMessageKey] = App_GlobalResources.Wording.InsertSuccess;
                        return RedirectToAction("Index");
                    }
                }

                return View(model);
            }

            return View(model);

            //if (Request.UrlReferrer != null)
            //    return Redirect(Request.UrlReferrer.AbsoluteUri);
            //return RedirectToAction("Index");
        }

        #endregion

        #region Detail
        public ActionResult Detail(int? Id)
        {
            var ProcessStage = ProcessStageRepository.GetProcessStageById(Id.Value);
            if (ProcessStage != null && ProcessStage.IsDeleted != true)
            {
                var model = new ProcessStageViewModel();
                AutoMapper.Mapper.Map(ProcessStage, model);

                if (model.CreatedUserId != Erp.BackOffice.Helpers.Common.CurrentUser.Id && Erp.BackOffice.Helpers.Common.CurrentUser.UserTypeId != 1)
                {
                    TempData["FailedMessage"] = "NotOwner";
                    return RedirectToAction("Index");
                }

                return View(model);
            }
            if (Request.UrlReferrer != null)
                return Redirect(Request.UrlReferrer.AbsoluteUri);
            return RedirectToAction("Index");
        }
        #endregion

        #region Delete
        [HttpPost]
        public ActionResult Delete()
        {
            try
            {
                string idDeleteAll = Request["DeleteId-checkbox"];
                string[] arrDeleteId = idDeleteAll.Split(',');
                for (int i = 0; i < arrDeleteId.Count(); i++)
                {
                    var item = ProcessStageRepository.GetProcessStageById(int.Parse(arrDeleteId[i], CultureInfo.InvariantCulture));
                    if (item != null)
                    {
                        if (item.CreatedUserId != Erp.BackOffice.Helpers.Common.CurrentUser.Id && Erp.BackOffice.Helpers.Common.CurrentUser.UserTypeId != 1)
                        {
                            TempData["FailedMessage"] = "NotOwner";
                            return RedirectToAction("Index");
                        }

                        item.IsDeleted = true;
                        ProcessStageRepository.UpdateProcessStage(item);
                    }
                }
                TempData[Globals.SuccessMessageKey] = App_GlobalResources.Wording.DeleteSuccess;
                return RedirectToAction("Index");
            }
            catch (DbUpdateException)
            {
                TempData[Globals.FailedMessageKey] = App_GlobalResources.Error.RelationError;
                return RedirectToAction("Index");
            }
        }
        #endregion
    }
}

Erp.BackOffice/Areas/Crm/Views/ProcessStage/Create.cshtml
@using Erp.BackOffice.App_GlobalResources
@using Erp.BackOffice.Helpers
@using Erp.BackOffice.Crm.Models

@model ProcessStageViewModel

@{
    ViewBag.Title = Wording.PageCreate_ProcessStage;

    Layout = "~/Views/Shared/" + (Request["IsPopup"] == null ? "ACE_AdminLayout.cshtml" : "_PopupLayout.cshtml");

}

@section HeadOfPage {
    @Html.ScriptTop_ChosenStyle()
}

@using (Html.BeginForm("Create", "ProcessStage", null, FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.ValidationSummary(true)

    <input type="hidden" value="@Request["IsPopup"]" name="IsPopup" />
    @Html.HiddenFor(model => model.ProcessId)

    @Html.CustomTextboxFor(model => model.Name, null, null, WidthType.span12)
    @Html.SpinnerFor(model => model.OrderNo, 100, 0, 1, SpinnerStyle.SpinnerStyle1, true)


    <button style="margin-top:10px" type="submit" class="btn btn-info" name="Submit" value="Save">
        <i class="ace-icon fa fa-save bigger-110"></i>
        @Wording.Save
    </button>
}

@section Scripts {
    <script>
        //truyền từ action create của controller qua khi thực hiện submit và return về lại view create, để nhận biết là được gọi theo dạng popup
        var closePopup = '@ViewBag.closePopup';
        $(document).ready(function () {
            //nếu là được gọi theo dạng popup từ form khác thì chạy đoạn code bên dưới
            if (closePopup != '') {
                var option = '<option value="@Model.Id" >@Model.Name</option>';
                //tên funtion có thể khác theo từng công việc riêng (đây chỉ là mẫu khi thêm mới sẽ gọi lại)
                window.parent.ClosePopupAndAppendSelect(option);
            }
        });
    </script>
    @Html.ScriptBottom_ValidationMvc()
    @Html.ScriptBottom_ChosenStyle()
}

Erp.BackOffice/Areas/Crm/Views/ProcessStage/Detail.cshtml
@using Erp.BackOffice.App_GlobalResources
@using Erp.BackOffice.Helpers
@using Erp.BackOffice.Crm.Models

@model ProcessStageViewModel

@{
    ViewBag.Title = Wording.PageDetail_ProcessStage;

    Layout = "~/Views/Shared/ACE_AdminLayout.cshtml";
}
<div class="page-header">
    <h1>
        @ViewBag.Title
    </h1>
</div>

<p>@Html.Button(Wording.Edit, ButtonType.aTag, ButtonColor.Info, ButtonSize.Mini, true, IconType.Edit, IconSize.Default, false, new { @href = Url.Action("Edit", "ProcessStage", new { Id = Model.Id }) })</p>

<div class="detail-view">
    <div class="row control-group">
        @Html.DetailViewItemFor2(model => model.Name)
    </div>
</div>
<p></p>
@*@{Html.RenderAction("SubList", "");}*@

@section Scripts {
    <script type="text/javascript">
        function CheckIsval() {
            if ($('[name="DeleteAll-checkbox"]').is(':checked') == false) {
                alert("Phải chọn ít nhất 1 item.");
                return false;
            }
            else {
                if (confirm('Bạn có chắc muốn xóa các item đã chọn ?')) {
                    return true;
                }
                else {
                    return false;
                }
            }
        }

        $('[name="Delete"]').click(function () {
            if (confirm('Bạn có chắc muốn xóa item ?')) {
                $(this).closest('tr').children('td').each(function (i, e) {
                    $(this).find("input.class-delete-all").prop("checked", true);
                    return true;
                })
            }
            else {
                return false;
            }

        })

    </script>
}

Erp.BackOffice/Areas/Crm/Views/ProcessStage/Edit.cshtml
@using Erp.BackOffice.App_GlobalResources
@using Erp.BackOffice.Helpers
@using Erp.BackOffice.Crm.Models

@model ProcessStageViewModel

@{
    ViewBag.Title = Wording.PageEdit_ProcessStage;

    Layout = "~/Views/Shared/" + (Request["IsPopup"] == null ? "ACE_AdminLayout.cshtml" : "_PopupLayout.cshtml");
}

@section HeadOfPage {
    @Html.ScriptTop_ChosenStyle()
}

@using (Html.BeginForm("Edit", "ProcessStage", null, FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.CreatedUserId)
    @Html.HiddenFor(model => model.AssignedUserId)
    @Html.HiddenFor(model => model.CreatedDate)
    @Html.HiddenFor(model => model.IsDeleted)
    @Html.HiddenFor(model => model.ProcessId)

    <input type="hidden" value="@Request["IsPopup"]" name="IsPopup" />
    
    @Html.CustomTextboxFor(model => model.Name, null, null, WidthType.span12)
    @Html.SpinnerFor(model => model.OrderNo, 100, 0, 1, SpinnerStyle.SpinnerStyle1, true)

    <button style="margin-top:10px" type="submit" class="btn btn-info" name="Submit" value="Save">
        <i class="ace-icon fa fa-save bigger-110"></i>
        @Wording.Save
    </button>
}

@section Scripts {

    @Html.ScriptBottom_ValidationMvc()
    @Html.ScriptBottom_ChosenStyle()
}

Erp.BackOffice/Areas/Crm/Views/ProcessStage/Index.cshtml
@model IQueryable<ProcessStageViewModel>

@using Erp.BackOffice.App_GlobalResources
@using Erp.BackOffice.Crm.Models
@using Erp.BackOffice.Helpers
@using GridMvc.Html

@{
    Layout = null;
}

<p>
    <a class="btn btn-mini btn-info" onclick="OpenPopup('@Url.Action("Create", "ProcessStage", new { area = "Crm", ProcessId = Request["ProcessId"], IsPopup = true })', 'Add stage', 500, 500)">
        <i class="ace-icon fa fa-plus bigger-120"></i>
        Add stage
    </a>
</p>

@foreach (var item in Model)
{
    <div class="widget-box widget-color-green">
        <div class="widget-header widget-header-small">
            <h6 class="widget-title smaller">
                <b>Stage @item.OrderNo:</b> @item.Name
                <a style="color:white" onclick="OpenPopup('@Url.Action("Edit", "ProcessStage", new { area = "Crm", Id = item.Id, IsPopup = true })', 'Edit stage', 500, 500)">
                    <i class="ace-icon fa fa-edit"></i>
                </a>
            </h6>
        </div>
        <div class="widget-body">
            <div class="widget-main">
                @{Html.RenderAction("Index", "ProcessStep", new { StageId = item.Id, ProcessEntity = ViewBag.ProcessEntity });}
            </div>
        </div>
    </div>
}

Erp.BackOffice/Areas/Crm/Views/ProcessStage/SubList.cshtml
@model IQueryable<ProcessStageViewModel>

@using Erp.BackOffice.App_GlobalResources
@using Erp.BackOffice.Crm.Models
@using Erp.BackOffice.Helpers
@using GridMvc.Html

@helper GridColumnCommand(int id)
{
    <div class="hidden-phone visible-desktop action-buttons" style="display: inline-block; float: left;">
        <p>
            <button name="Delete" value="Delete" type="submit" class="btn btn-mini btn-danger">
                <i class="ace-icon fa fa-trash bigger-120"></i>
            </button>
        </p>
    </div>
}

@helper GridColumnName(string name, int id)
{
    @*if (string.IsNullOrEmpty(name))
        {
            <a href="@Url.Action("Edit", "Branch", new { Id = id })">No Title</a>
        }
        else
        {
            <a href="@Url.Action("Edit", "Branch", new { Id = id })">@name</a>
        }*@
    @name
}

@helper CheckDeleteColumns(int Id)
{
    <label>
        <input class="ace class-delete-all" type="checkbox" name="DeleteAll-checkbox" value="@Id">
        <span class="lbl"></span>
    </label>
}

@helper BuildCheckAll()
{
    <label>
        <input class="ace" type="checkbox" name="checkAll" id="checkAll" />
        <span class="lbl"></span>
    </label>
}

<div class="widget-box">
    <div class="widget-header">
        <h5 class="widget-title">Sub List ProcessStage</h5>
        <div class="widget-toolbar">
            <a href="#" data-action="collapse">
                <i class="ace-icon fa fa-chevron-up"></i>
            </a>
        </div>
    </div>
    <div class="widget-body">
        <div class="widget-main">
            @using (Html.BeginForm("DeleteOnSubList", "ProcessStage", FormMethod.Post))
            {
                <p>
                    @if (Erp.BackOffice.Filters.SecurityFilter.AccessRight("Create", "ProcessStage", "Crm"))
                    {
                        @Html.Button(Wording.CreateNew, ButtonType.aTag, ButtonColor.Info, ButtonSize.Mini, true, IconType.Plus, IconSize.Default, false, new { @href = Url.Action("Create", "ProcessStage") })
                    }
                    @if (Erp.BackOffice.Filters.SecurityFilter.AccessRight("DeleteOnSubList", "ProcessStage", "Crm"))
                    {
                        <button name="DeleteAll" value="DeleteAll" type="submit" class="btn btn-mini btn-danger" onclick="return CheckIsval();">
                            <i class="ace-icon fa fa-trash bigger-120"></i>
                            @Wording.Delete
                        </button>
                    }
                </p>

                @Html.Grid(Model).Columns(columns =>
                {
                    columns.Add().Titled(BuildCheckAll().ToHtmlString()).SetWidth(20).Sanitized(false).Encoded(false).RenderValueAs(n => CheckDeleteColumns(n.Id));
                    columns.Add().Titled(Html.DisplayNameFor(u => u.FirstOrDefault().Name).ToString()).Sortable(false).Sanitized(false).Encoded(false).RenderValueAs(u => GridColumnName(u.Name, u.Id));
                    columns.Add(u => u.Id).Titled(Wording.Action).Sanitized(false).Encoded(false).RenderValueAs(u => GridColumnCommand(u.Id)).SetWidth(20);
                }).WithPaging(10)
            }
        </div>
    </div>
</div>